<a href="https://colab.research.google.com/github/haabibfahadkp/introduction-to-python/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales (1).csv to Supermarket_sales (1).csv


In [6]:
import pandas
dataframe=pandas.read_csv("Supermarket_sales (1).csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [9]:
dataframe.head(10)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty      58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel      86.31         7  30.2085  634.3785   2/8/2019   
5  Electronic accessories      85.39         7  29.8865  627.6165  3/25/2019   
6  Electronic accessories      68.84         6  20.6520  433.6920  2/25/2019   
7      Home and lifestyle      73.56        10  36.7800  772.3800  2/24/2019   
8       Health and beauty      36.26         2   3.6260   76.1460  1/10/2019   
9      Food and beverages      54.84         3   8.2260  172.7460  2/20/2019   

    Time      Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  13:08      Ewallet  522.83                 4.761905        26.1415     9.1  
1  10:29         Cash   76.40                 4.761905         3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905        16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905        23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905        30.2085     5.3  
5  18:30      Ewallet  597.73                 4.761905        29.8865     4.1  
6  14:36      Ewallet  413.04                 4.761905        20.6520     5.8  
7  11:38      Ewallet  735.60                 4.761905        36.7800     8.0  
8  17:15  Credit card   72.52                 4.761905         3.6260     7.2  
9  13:27  Credit card  164.52                 4.761905         8.2260     5.9

In [10]:
dataframe.tail(10)

No    InvoiceID Branch       City Customertype  Gender  \
990   991  886-18-2897      A     Yangon       Normal  Female   
991   992  602-16-6955      B   Mandalay       Normal  Female   
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
990      Food and beverages      56.56         5  14.1400   296.9400   
991       Sports and travel      76.60        10  38.3000   804.3000   
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6900  1022.4900   
997      Food and beverages      31.84         1   1.5920    33.4320   
998      Home and lifestyle      65.82         1   3.2910    69.1110   
999     Fashion accessories      88.34         7  30.9190   649.2990   

          Date   Time      Payment    cogs  gross_margin_percentage  \
990  3/22/2019  19:06  Credit card  282.80                 4.761905   
991  1/24/2019  18:10      Ewallet  766.00                 4.761905   
992  3/10/2019  20:46      Ewallet  116.06                 4.761905   
993  2/22/2019  18:35      Ewallet  174.90                 4.761905   
994  2/18/2019  11:40      Ewallet   60.95                 4.761905   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
996   3/2/2019  17:16      Ewallet  973.80                 4.761905   
997   2/9/2019  13:22         Cash   31.84                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   
999  2/18/2019  13:28         Cash  618.38                 4.761905   

     gross_iincome  Rating  
990        14.1400     4.5  
991        38.3000     6.0  
992         5.8030     8.8  
993         8.7450     6.6  
994         3.0475     5.9  
995         2.0175     6.2  
996        48.6900     4.4  
997         1.5920     7.7  
998         3.2910     4.1  
999        30.9190     6.6

In [11]:
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [12]:
dataframe.loc[0]

No                                         1
InvoiceID                        750-67-8428
Branch                                     A
City                                  Yangon
Customertype                          Member
Gender                                Female
Productline                Health and beauty
Unitprice                              74.69
Quantity                                   7
Tax                                  26.1415
Total                               548.9715
Date                                1/5/2019
Time                                   13:08
Payment                              Ewallet
cogs                                  522.83
gross_margin_percentage             4.761905
gross_iincome                        26.1415
Rating                                   9.1
Name: 0, dtype: object

In [13]:
dataframe.loc[3]

No                                         4
InvoiceID                        123-19-1176
Branch                                     A
City                                  Yangon
Customertype                          Member
Gender                                  Male
Productline                Health and beauty
Unitprice                              58.22
Quantity                                   8
Tax                                   23.288
Total                                489.048
Date                               1/27/2019
Time                                   20:33
Payment                              Ewallet
cogs                                  465.76
gross_margin_percentage             4.761905
gross_iincome                         23.288
Rating                                   8.4
Name: 3, dtype: object

In [16]:
dataframe[["City"]]

City
0       Yangon
1    Naypyitaw
2       Yangon
3       Yangon
4       Yangon
..         ...
995  Naypyitaw
996   Mandalay
997     Yangon
998     Yangon
999     Yangon

[1000 rows x 1 columns]

In [18]:
dataframe[["City","Branch"]]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [20]:
dataframe=dataframe.drop(["Tax"],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [24]:
dataframe=dataframe.drop([2],axis=0)
dataframe.head(2)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   

              Productline  Unitprice  Quantity     Total      Date   Time  \
0       Health and beauty      74.69         7  548.9715  1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200  3/8/2019  10:29   

   Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  Ewallet  522.83                 4.761905        26.1415     9.1  
1     Cash   76.40                 4.761905         3.8200     9.6

In [26]:
dataframe.Unitprice.max

<bound method NDFrame._add_numeric_operations.<locals>.max of 0      74.69
1      15.28
3      58.22
4      86.31
5      85.39
       ...  
995    40.35
996    97.38
997    31.84
998    65.82
999    88.34
Name: Unitprice, Length: 999, dtype: float64>

In [27]:
dataframe.Unitprice.max()

99.96

In [29]:
dataframe.Unitprice.idxmax()

122

In [30]:
dataframe.Unitprice.min()

10.08

In [31]:
dataframe.City.count

<bound method Series.count of 0         Yangon
1      Naypyitaw
3         Yangon
4         Yangon
5      Naypyitaw
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 999, dtype: object>

In [32]:
dataframe.Unitprice.mean()

55.681481481481484

In [38]:
dataframe.loc[dataframe["Customertype"] =="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
12    13  365-64-0515      A     Yangon       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Total       Date   Time  \
1    Electronic accessories      15.28         5    80.2200   3/8/2019  10:29   
4         Sports and travel      86.31         7   634.3785   2/8/2019  10:37   
5    Electronic accessories      85.39         7   627.6165  3/25/2019  18:30   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
12   Electronic accessories      46.95         5   246.4875  2/12/2019  10:25   
..                      ...        ...       ...        ...        ...    ...   
992  Electronic accessories      58.03         2   121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10   183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1    42.3675  1/29/2019  13:46   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
998      Home and lifestyle      65.82         1    69.1110  2/22/2019  15:33   

     Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
1       Cash   76.40                 4.761905         3.8200     9.6  
4    Ewallet  604.17                 4.761905        30.2085     5.3  
5    Ewallet  597.73                 4.761905        29.8865     4.1  
7    Ewallet  735.60                 4.761905        36.7800     8.0  
12   Ewallet  234.75                 4.761905        11.7375     7.1  
..       ...     ...                      ...            ...     ...  
992  Ewallet  116.06                 4.761905         5.8030     8.8  
993  Ewallet  174.90                 4.761905         8.7450     6.6  
995  Ewallet   40.35                 4.761905         2.0175     6.2  
996  Ewallet  973.80                 4.761905        48.6900     4.4  
998     Cash   65.82                 4.761905         3.2910     4.1  

[498 rows x 17 columns]

In [42]:
dataframe.loc[dataframe["Gender"]=="Male"]

No    InvoiceID Branch       City Customertype Gender  \
3      4  123-19-1176      A     Yangon       Member   Male   
4      5  373-73-7910      A     Yangon       Normal   Male   
5      6  699-14-3026      C  Naypyitaw       Normal   Male   
11    12  529-56-3974      B   Mandalay       Member   Male   
13    14  252-56-2699      A     Yangon       Normal   Male   
..   ...          ...    ...        ...          ...    ...   
992  993  745-74-0715      A     Yangon       Normal   Male   
993  994  690-01-6631      B   Mandalay       Normal   Male   
995  996  233-67-5758      C  Naypyitaw       Normal   Male   
997  998  727-02-1313      A     Yangon       Member   Male   
998  999  347-56-2442      A     Yangon       Normal   Male   

                Productline  Unitprice  Quantity     Total       Date   Time  \
3         Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4         Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
5    Electronic accessories      85.39         7  627.6165  3/25/2019  18:30   
11   Electronic accessories      25.51         4  107.1420   3/9/2019  17:03   
13       Food and beverages      43.19        10  453.4950   2/7/2019  16:48   
..                      ...        ...       ...       ...        ...    ...   
992  Electronic accessories      58.03         2  121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10  183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1   42.3675  1/29/2019  13:46   
997      Food and beverages      31.84         1   33.4320   2/9/2019  13:22   
998      Home and lifestyle      65.82         1   69.1110  2/22/2019  15:33   

     Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
3    Ewallet  465.76                 4.761905        23.2880     8.4  
4    Ewallet  604.17                 4.761905        30.2085     5.3  
5    Ewallet  597.73                 4.761905        29.8865     4.1  
11      Cash  102.04                 4.761905         5.1020     6.8  
13   Ewallet  431.90                 4.761905        21.5950     8.2  
..       ...     ...                      ...            ...     ...  
992  Ewallet  116.06                 4.761905         5.8030     8.8  
993  Ewallet  174.90                 4.761905         8.7450     6.6  
995  Ewallet   40.35                 4.761905         2.0175     6.2  
997     Cash   31.84                 4.761905         1.5920     7.7  
998     Cash   65.82                 4.761905         3.2910     4.1  

[498 rows x 17 columns]

In [45]:
import numpy as np
student_marks=[[12,14,10],[15,19,20],[11,15,19]]
marksarray=np.array(student_marks)
print(marksarray)


[[12 14 10]
 [15 19 20]
 [11 15 19]]


In [46]:
import numpy as np
student_marks=[[22,21],[25,10],[24,21],[17,25]]
marksarray=np.array(student_marks)
print(marksarray)


[[22 21]
 [25 10]
 [24 21]
 [17 25]]


In [47]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [48]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
values2=np.arange(5,11)
print(values2)

[ 5  6  7  8  9 10]


In [51]:
values3=np.arange(50,61)
print(values3)

[50 51 52 53 54 55 56 57 58 59 60]


In [52]:
values4=np.arange(70,101,3)
print(values4)

[ 70  73  76  79  82  85  88  91  94  97 100]


In [53]:
zeroarray=np.zeros((8))
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [54]:
zeroarray=np.zeros((4,2))
print(zeroarray)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [55]:
onearray=np.ones(5)
print(onearray)

[1. 1. 1. 1. 1.]


In [58]:
onearray=np.ones((8,2))
print(onearray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [59]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
len(zeroarray)

4

In [64]:
firstarray=np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])
print(firstarray.shape)
secondarray=firstarray.reshape(4,3)
print(firstarray)




(3, 4)
[[10 20 30 40]
 [ 2  4  6  8]
 [ 5 10 15 20]]


In [66]:
values=np.random.randint(1,3,5)
print(values)

[2 2 1 2 1]


In [67]:
values=np.random.randint(44,48,6)
print(values)

[44 44 45 44 45 46]


In [68]:
randshaped=np.random.randint(25,50,(5,3))
print(randshaped)

[[35 26 42]
 [44 26 26]
 [34 32 28]
 [29 37 33]
 [33 35 43]]
